version: "3.7"
services:
  hfddbackend:
    image: hfdd-backend
    container_name: hfdd-backend
    build:
      context: ./backend
      dockerfile: Dockerfile-prod
    ports:
      - "8082:8082"
  hfddfrontend:
    image: hfdd-ui
    container_name: hfdd-ui
    build:
      context: ./hfddFrontend
      dockerfile: Dockerfile-prod
    ports:
      - "80:80"
    depends_on:
      - hfddbackend
