FROM amazoncorretto:20 AS build

WORKDIR /workspace/app
COPY . .

WORKDIR /workspace/app/hfdd-backend

RUN chmod +x ./gradlew
RUN ./gradlew build -x test


FROM amazoncorretto:20-alpine

COPY --from=build /workspace/app/hfdd-backend/build/libs/hfdd-backend-0.0.1-SNAPSHOT.jar ./hfddBackend.jar

EXPOSE 8082
ENTRYPOINT ["java", "-jar", "hfddBackend.jar"]

